CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE app_monitors (
        id uuid NOT NULL,
        app_key character varying(128) NOT NULL,
        env character varying(64) NOT NULL,
        version character varying(256),
        source_uuid character varying(64),
        tenant_id character varying(64),
        tenant_name character varying(128),
        user_id character varying(64),
        user_name character varying(64),
        url character varying(2048),
        browser character varying(512),
        message text,
        stack text,
        status integer NOT NULL,
        remark character varying(2048),
        created_at timestamp with time zone NOT NULL,
        resolved_by_user_id character varying(64),
        resolved_by_user_name character varying(64),
        resolved_at timestamp with time zone,
        CONSTRAINT "PK_app_monitors" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE applications (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(64) NOT NULL,
        app_key character varying(128) NOT NULL,
        project_type character varying(32) NOT NULL DEFAULT 'fe',
        deploy_key character varying(128),
        git_id integer NOT NULL,
        registry_key character varying(64) NOT NULL DEFAULT 'fe',
        git_name character varying(256) NOT NULL,
        git_repo character varying(512) NOT NULL,
        main_branch character varying(128) NOT NULL DEFAULT 'main',
        pre_branch character varying(128) NOT NULL DEFAULT 'pre',
        stage_branch character varying(128) NOT NULL DEFAULT 'stage',
        dev_branch character varying(128) NOT NULL DEFAULT 'dev',
        git_namespace_id integer NOT NULL,
        trigger_token character varying(128) NOT NULL,
        owner_user_id character varying(64) NOT NULL,
        owner_name character varying(64) NOT NULL,
        status integer NOT NULL,
        remark character varying(1024),
        ranchers jsonb,
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        updated_by_user_id character varying(64) NOT NULL,
        updated_by_user_name character varying(64),
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_applications" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE integration_releases (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        version character varying(128) NOT NULL,
        name character varying(512),
        branch character varying(256),
        remark character varying(2048),
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_integration_releases" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE requirements (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(512) NOT NULL,
        status integer NOT NULL,
        document_url character varying(1024) NOT NULL,
        priority integer,
        remark character varying(2048),
        online_at timestamp with time zone,
        submitted_test_at timestamp with time zone,
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        updated_by_user_id character varying(64) NOT NULL,
        updated_by_user_name character varying(64),
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_requirements" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id character varying(64) NOT NULL,
        ding_talk_user_id character varying(64),
        manager_user_id character varying(64),
        manager_ding_talk_user_id character varying(64),
        email character varying(128),
        name character varying(64) NOT NULL,
        real_name character varying(64),
        mobile character varying(32) NOT NULL,
        role integer NOT NULL,
        status integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE sub_applications (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        parent_application_id integer NOT NULL,
        name character varying(64) NOT NULL,
        app_key character varying(128) NOT NULL,
        platform character varying(32),
        deploy_key character varying(128),
        git_id integer NOT NULL,
        registry_key character varying(64) NOT NULL DEFAULT 'fe',
        git_name character varying(256) NOT NULL,
        git_repo character varying(512) NOT NULL,
        main_branch character varying(128) NOT NULL DEFAULT 'main',
        pre_branch character varying(128) NOT NULL DEFAULT 'pre',
        stage_branch character varying(128) NOT NULL DEFAULT 'stage',
        dev_branch character varying(128) NOT NULL DEFAULT 'dev',
        prod_site_address character varying(256) NOT NULL,
        pre_site_address character varying(256) NOT NULL,
        stage_site_address character varying(256) NOT NULL,
        dev_site_address character varying(256) NOT NULL,
        git_namespace_id integer NOT NULL,
        trigger_token character varying(128) NOT NULL,
        remark character varying(1024),
        public_path character varying(256),
        upload_to_oss boolean NOT NULL DEFAULT FALSE,
        app_type character varying(32) NOT NULL DEFAULT 'saas',
        variables jsonb,
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        updated_by_user_id character varying(64) NOT NULL,
        updated_by_user_name character varying(64),
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_sub_applications" PRIMARY KEY (id),
        CONSTRAINT "FK_sub_applications_applications_parent_application_id" FOREIGN KEY (parent_application_id) REFERENCES applications (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE requirement_developers (
        requirement_id integer NOT NULL,
        user_id integer NOT NULL,
        CONSTRAINT "PK_requirement_developers" PRIMARY KEY (requirement_id, user_id),
        CONSTRAINT "FK_requirement_developers_requirements_requirement_id" FOREIGN KEY (requirement_id) REFERENCES requirements (id) ON DELETE CASCADE,
        CONSTRAINT "FK_requirement_developers_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE requirement_followers (
        requirement_id integer NOT NULL,
        user_id integer NOT NULL,
        CONSTRAINT "PK_requirement_followers" PRIMARY KEY (requirement_id, user_id),
        CONSTRAINT "FK_requirement_followers_requirements_requirement_id" FOREIGN KEY (requirement_id) REFERENCES requirements (id) ON DELETE CASCADE,
        CONSTRAINT "FK_requirement_followers_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE iterations (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        application_id integer NOT NULL,
        sub_application_id integer,
        integration_release_id integer,
        name character varying(512) NOT NULL,
        application_name character varying(128) NOT NULL,
        sub_application_name character varying(128),
        branch character varying(256) NOT NULL,
        original_commit character varying(64),
        status integer NOT NULL,
        remark character varying(2048),
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        updated_by_user_id character varying(64) NOT NULL,
        updated_by_user_name character varying(64),
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_iterations" PRIMARY KEY (id),
        CONSTRAINT "FK_iterations_applications_application_id" FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_iterations_integration_releases_integration_release_id" FOREIGN KEY (integration_release_id) REFERENCES integration_releases (id) ON DELETE SET NULL,
        CONSTRAINT "FK_iterations_sub_applications_sub_application_id" FOREIGN KEY (sub_application_id) REFERENCES sub_applications (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE pipeline_templates (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(128) NOT NULL,
        template_key character varying(128),
        status integer NOT NULL DEFAULT 1,
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        updated_by_user_id character varying(64),
        updated_by_user_name character varying(64),
        updated_at timestamp with time zone NOT NULL,
        "ApplicationId" integer,
        "SubApplicationId" integer,
        CONSTRAINT "PK_pipeline_templates" PRIMARY KEY (id),
        CONSTRAINT "FK_pipeline_templates_applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES applications (id),
        CONSTRAINT "FK_pipeline_templates_sub_applications_SubApplicationId" FOREIGN KEY ("SubApplicationId") REFERENCES sub_applications (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE integration_release_apps (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        integration_release_id integer NOT NULL,
        application_id integer NOT NULL,
        sub_application_id integer NOT NULL,
        app_key character varying(128) NOT NULL,
        application_name character varying(128) NOT NULL,
        sub_application_name character varying(128) NOT NULL,
        iteration_id integer NOT NULL,
        CONSTRAINT "PK_integration_release_apps" PRIMARY KEY (id),
        CONSTRAINT "FK_integration_release_apps_applications_application_id" FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_integration_release_apps_integration_releases_integration_r~" FOREIGN KEY (integration_release_id) REFERENCES integration_releases (id) ON DELETE CASCADE,
        CONSTRAINT "FK_integration_release_apps_iterations_iteration_id" FOREIGN KEY (iteration_id) REFERENCES iterations (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_integration_release_apps_sub_applications_sub_application_id" FOREIGN KEY (sub_application_id) REFERENCES sub_applications (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE iteration_requirements (
        iteration_id integer NOT NULL,
        requirement_id integer NOT NULL,
        CONSTRAINT "PK_iteration_requirements" PRIMARY KEY (iteration_id, requirement_id),
        CONSTRAINT "FK_iteration_requirements_iterations_iteration_id" FOREIGN KEY (iteration_id) REFERENCES iterations (id) ON DELETE CASCADE,
        CONSTRAINT "FK_iteration_requirements_requirements_requirement_id" FOREIGN KEY (requirement_id) REFERENCES requirements (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE pipeline_template_stages (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        pipeline_template_id integer NOT NULL,
        name character varying(128) NOT NULL,
        seq integer NOT NULL,
        CONSTRAINT "PK_pipeline_template_stages" PRIMARY KEY (id),
        CONSTRAINT "FK_pipeline_template_stages_pipeline_templates_pipeline_templa~" FOREIGN KEY (pipeline_template_id) REFERENCES pipeline_templates (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE pipelines (
        id uuid NOT NULL,
        app_key character varying(128) NOT NULL,
        iteration_id integer NOT NULL,
        repo_id integer NOT NULL,
        registry_key character varying(64) NOT NULL DEFAULT 'fe',
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        status integer NOT NULL,
        stage_seq integer NOT NULL DEFAULT -1,
        pipeline_template_id integer NOT NULL,
        branch character varying(256) NOT NULL,
        content character varying(2048),
        swim_lane character varying(128),
        force_update integer,
        extra jsonb,
        CONSTRAINT "PK_pipelines" PRIMARY KEY (id),
        CONSTRAINT "FK_pipelines_pipeline_templates_pipeline_template_id" FOREIGN KEY (pipeline_template_id) REFERENCES pipeline_templates (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE pipeline_template_jobs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        pipeline_template_stage_id integer NOT NULL,
        name character varying(128) NOT NULL,
        job_key character varying(128) NOT NULL,
        stage_seq integer NOT NULL,
        extra jsonb,
        CONSTRAINT "PK_pipeline_template_jobs" PRIMARY KEY (id),
        CONSTRAINT "FK_pipeline_template_jobs_pipeline_template_stages_pipeline_te~" FOREIGN KEY (pipeline_template_stage_id) REFERENCES pipeline_template_stages (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE deploys (
        id uuid NOT NULL,
        pipeline_id uuid,
        app_key character varying(128) NOT NULL,
        iteration_id integer,
        created_by_user_id character varying(64) NOT NULL,
        created_by_user_name character varying(64),
        created_at timestamp with time zone NOT NULL,
        env character varying(64) NOT NULL,
        version character varying(256),
        use_vpn boolean,
        deploy_type integer,
        swim_lane character varying(128),
        integration_release_version character varying(128),
        CONSTRAINT "PK_deploys" PRIMARY KEY (id),
        CONSTRAINT "FK_deploys_pipelines_pipeline_id" FOREIGN KEY (pipeline_id) REFERENCES pipelines (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE TABLE pipeline_jobs (
        id uuid NOT NULL,
        pipeline_id uuid NOT NULL,
        stage_seq integer NOT NULL,
        job_key character varying(128) NOT NULL,
        status integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        unit_key character varying(256),
        extra jsonb,
        CONSTRAINT "PK_pipeline_jobs" PRIMARY KEY (id),
        CONSTRAINT "FK_pipeline_jobs_pipelines_pipeline_id" FOREIGN KEY (pipeline_id) REFERENCES pipelines (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX ix_app_monitors_app_key_env ON app_monitors (app_key, env);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX ix_app_monitors_status ON app_monitors (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_applications_app_key ON applications (app_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX ix_deploys_app_key ON deploys (app_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX ix_deploys_pipeline_id ON deploys (pipeline_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_integration_release_apps_application_id" ON integration_release_apps (application_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_integration_release_apps_integration_release_id" ON integration_release_apps (integration_release_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_integration_release_apps_iteration_id" ON integration_release_apps (iteration_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_integration_release_apps_sub_application_id" ON integration_release_apps (sub_application_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_integration_releases_version ON integration_releases (version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_iteration_requirements_requirement_id" ON iteration_requirements (requirement_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_iterations_application_id" ON iterations (application_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_iterations_integration_release_id" ON iterations (integration_release_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_iterations_sub_application_id" ON iterations (sub_application_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_pipeline_jobs_pipeline_stage_job ON pipeline_jobs (pipeline_id, stage_seq, job_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_pipeline_template_jobs_pipeline_template_stage_id" ON pipeline_template_jobs (pipeline_template_stage_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_pipeline_template_stages_pipeline_template_id" ON pipeline_template_stages (pipeline_template_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_pipeline_templates_ApplicationId" ON pipeline_templates ("ApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_pipeline_templates_name ON pipeline_templates (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_pipeline_templates_SubApplicationId" ON pipeline_templates ("SubApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_pipeline_templates_template_key ON pipeline_templates (template_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX ix_pipelines_app_key ON pipelines (app_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX ix_pipelines_iteration_id ON pipelines (iteration_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_pipelines_pipeline_template_id" ON pipelines (pipeline_template_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_requirement_developers_user_id" ON requirement_developers (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_requirement_followers_user_id" ON requirement_followers (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_sub_applications_app_key ON sub_applications (app_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX "IX_sub_applications_parent_application_id" ON sub_applications (parent_application_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE INDEX ix_users_ding_talk_user_id ON users (ding_talk_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_mobile ON users (mobile);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818033450_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260818033450_InitialCreate', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE pipeline_templates DROP CONSTRAINT "FK_pipeline_templates_applications_ApplicationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    DROP INDEX "IX_pipeline_templates_ApplicationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE pipeline_templates DROP COLUMN "ApplicationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE applications DROP COLUMN deploy_key;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE applications DROP COLUMN dev_branch;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE applications DROP COLUMN main_branch;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE applications DROP COLUMN pre_branch;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE applications DROP COLUMN ranchers;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    ALTER TABLE applications DROP COLUMN stage_branch;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818054910_RemoveApplicationFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260818054910_RemoveApplicationFields', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818055832_AddApplicationFields') THEN
    ALTER TABLE applications ADD deploy_key character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818055832_AddApplicationFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260818055832_AddApplicationFields', '10.0.11');
    END IF;
END $EF$;
COMMIT;

