// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetaServerDbContext))]
    [Migration("20260818033450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AppMonitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("app_key");

                    b.Property<string>("Browser")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("browser");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Env")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("env");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Remark")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("remark");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("ResolvedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resolved_by_user_name");

                    b.Property<string>("SourceUuid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_uuid");

                    b.Property<string>("Stack")
                        .HasColumnType("text")
                        .HasColumnName("stack");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_name");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_name");

                    b.Property<string>("Version")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_app_monitors_status");

                    b.HasIndex("AppKey", "Env")
                        .HasDatabaseName("ix_app_monitors_app_key_env");

                    b.ToTable("app_monitors", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("app_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<string>("DeployKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deploy_key");

                    b.Property<string>("DevBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("dev")
                        .HasColumnName("dev_branch");

                    b.Property<int>("GitId")
                        .HasColumnType("integer")
                        .HasColumnName("git_id");

                    b.Property<string>("GitName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("git_name");

                    b.Property<int>("GitNamespaceId")
                        .HasColumnType("integer")
                        .HasColumnName("git_namespace_id");

                    b.Property<string>("GitRepo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("git_repo");

                    b.Property<string>("MainBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("main")
                        .HasColumnName("main_branch");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PreBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("pre")
                        .HasColumnName("pre_branch");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("fe")
                        .HasColumnName("project_type");

                    b.Property<JsonDocument>("Ranchers")
                        .HasColumnType("jsonb")
                        .HasColumnName("ranchers");

                    b.Property<string>("RegistryKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("fe")
                        .HasColumnName("registry_key");

                    b.Property<string>("Remark")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("remark");

                    b.Property<string>("StageBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("stage")
                        .HasColumnName("stage_branch");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TriggerToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trigger_token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UpdatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_name");

                    b.HasKey("Id");

                    b.HasIndex("AppKey")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_app_key");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Deploy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("app_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<int?>("DeployType")
                        .HasColumnType("integer")
                        .HasColumnName("deploy_type");

                    b.Property<string>("Env")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("env");

                    b.Property<string>("IntegrationReleaseVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("integration_release_version");

                    b.Property<int?>("IterationId")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_id");

                    b.Property<Guid?>("PipelineId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_id");

                    b.Property<string>("SwimLane")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("swim_lane");

                    b.Property<bool?>("UseVpn")
                        .HasColumnType("boolean")
                        .HasColumnName("use_vpn");

                    b.Property<string>("Version")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AppKey")
                        .HasDatabaseName("ix_deploys_app_key");

                    b.HasIndex("PipelineId")
                        .HasDatabaseName("ix_deploys_pipeline_id");

                    b.ToTable("deploys", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.IntegrationRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("remark");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_releases_version");

                    b.ToTable("integration_releases", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.IntegrationReleaseApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("app_key");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("application_name");

                    b.Property<int>("IntegrationReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("integration_release_id");

                    b.Property<int>("IterationId")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_id");

                    b.Property<int>("SubApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_application_id");

                    b.Property<string>("SubApplicationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sub_application_name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("IntegrationReleaseId");

                    b.HasIndex("IterationId");

                    b.HasIndex("SubApplicationId");

                    b.ToTable("integration_release_apps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Iteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("application_name");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<int?>("IntegrationReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("integration_release_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("OriginalCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("original_commit");

                    b.Property<string>("Remark")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SubApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_application_id");

                    b.Property<string>("SubApplicationName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sub_application_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UpdatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("IntegrationReleaseId");

                    b.HasIndex("SubApplicationId");

                    b.ToTable("iterations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("app_key");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("branch");

                    b.Property<string>("Content")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<JsonDocument>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<int?>("ForceUpdate")
                        .HasColumnType("integer")
                        .HasColumnName("force_update");

                    b.Property<int>("IterationId")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_id");

                    b.Property<int>("PipelineTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("pipeline_template_id");

                    b.Property<string>("RegistryKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("fe")
                        .HasColumnName("registry_key");

                    b.Property<int>("RepoId")
                        .HasColumnType("integer")
                        .HasColumnName("repo_id");

                    b.Property<int>("StageSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1)
                        .HasColumnName("stage_seq");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SwimLane")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("swim_lane");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppKey")
                        .HasDatabaseName("ix_pipelines_app_key");

                    b.HasIndex("IterationId")
                        .HasDatabaseName("ix_pipelines_iteration_id");

                    b.HasIndex("PipelineTemplateId");

                    b.ToTable("pipelines", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.PipelineJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_key");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_id");

                    b.Property<int>("StageSeq")
                        .HasColumnType("integer")
                        .HasColumnName("stage_seq");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UnitKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("unit_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId", "StageSeq", "JobKey")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_jobs_pipeline_stage_job");

                    b.ToTable("pipeline_jobs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<int?>("SubApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("template_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UpdatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_templates_name");

                    b.HasIndex("SubApplicationId");

                    b.HasIndex("TemplateKey")
                        .IsUnique()
                        .HasDatabaseName("ix_pipeline_templates_template_key");

                    b.ToTable("pipeline_templates", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplateJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("PipelineTemplateStageId")
                        .HasColumnType("integer")
                        .HasColumnName("pipeline_template_stage_id");

                    b.Property<int>("StageSeq")
                        .HasColumnType("integer")
                        .HasColumnName("stage_seq");

                    b.HasKey("Id");

                    b.HasIndex("PipelineTemplateStageId");

                    b.ToTable("pipeline_template_jobs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplateStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("PipelineTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("pipeline_template_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.HasKey("Id");

                    b.HasIndex("PipelineTemplateId");

                    b.ToTable("pipeline_template_stages", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("document_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OnlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("online_at");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Remark")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedTestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_test_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UpdatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_name");

                    b.HasKey("Id");

                    b.ToTable("requirements", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SubApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("app_key");

                    b.Property<string>("AppType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("saas")
                        .HasColumnName("app_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_name");

                    b.Property<string>("DeployKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deploy_key");

                    b.Property<string>("DevBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("dev")
                        .HasColumnName("dev_branch");

                    b.Property<string>("DevSiteAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dev_site_address");

                    b.Property<int>("GitId")
                        .HasColumnType("integer")
                        .HasColumnName("git_id");

                    b.Property<string>("GitName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("git_name");

                    b.Property<int>("GitNamespaceId")
                        .HasColumnType("integer")
                        .HasColumnName("git_namespace_id");

                    b.Property<string>("GitRepo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("git_repo");

                    b.Property<string>("MainBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("main")
                        .HasColumnName("main_branch");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("ParentApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_application_id");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<string>("PreBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("pre")
                        .HasColumnName("pre_branch");

                    b.Property<string>("PreSiteAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pre_site_address");

                    b.Property<string>("ProdSiteAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("prod_site_address");

                    b.Property<string>("PublicPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("public_path");

                    b.Property<string>("RegistryKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("fe")
                        .HasColumnName("registry_key");

                    b.Property<string>("Remark")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("remark");

                    b.Property<string>("StageBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("stage")
                        .HasColumnName("stage_branch");

                    b.Property<string>("StageSiteAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("stage_site_address");

                    b.Property<string>("TriggerToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trigger_token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UpdatedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_user_name");

                    b.Property<bool>("UploadToOss")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("upload_to_oss");

                    b.Property<JsonDocument>("Variables")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.HasKey("Id");

                    b.HasIndex("AppKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sub_applications_app_key");

                    b.HasIndex("ParentApplicationId");

                    b.ToTable("sub_applications", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DingTalkUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ding_talk_user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<string>("ManagerDingTalkUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manager_ding_talk_user_id");

                    b.Property<string>("ManagerUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manager_user_id");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("RealName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("real_name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DingTalkUserId")
                        .HasDatabaseName("ix_users_ding_talk_user_id");

                    b.HasIndex("Mobile")
                        .IsUnique()
                        .HasDatabaseName("ix_users_mobile");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("iteration_requirements", b =>
                {
                    b.Property<int>("iteration_id")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_id");

                    b.Property<int>("requirement_id")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_id");

                    b.HasKey("iteration_id", "requirement_id");

                    b.HasIndex("requirement_id");

                    b.ToTable("iteration_requirements", (string)null);
                });

            modelBuilder.Entity("requirement_developers", b =>
                {
                    b.Property<int>("requirement_id")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_id");

                    b.Property<int>("user_id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("requirement_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("requirement_developers", (string)null);
                });

            modelBuilder.Entity("requirement_followers", b =>
                {
                    b.Property<int>("requirement_id")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_id");

                    b.Property<int>("user_id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("requirement_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("requirement_followers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Deploy", b =>
                {
                    b.HasOne("Domain.Entities.Pipelines.Pipeline", "Pipeline")
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Domain.Entities.IntegrationReleaseApp", b =>
                {
                    b.HasOne("Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.IntegrationRelease", "IntegrationRelease")
                        .WithMany("ReleaseApps")
                        .HasForeignKey("IntegrationReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Iteration", "Iteration")
                        .WithMany()
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SubApplication", "SubApplication")
                        .WithMany()
                        .HasForeignKey("SubApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("IntegrationRelease");

                    b.Navigation("Iteration");

                    b.Navigation("SubApplication");
                });

            modelBuilder.Entity("Domain.Entities.Iteration", b =>
                {
                    b.HasOne("Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.IntegrationRelease", "IntegrationRelease")
                        .WithMany()
                        .HasForeignKey("IntegrationReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.SubApplication", "SubApplication")
                        .WithMany()
                        .HasForeignKey("SubApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("IntegrationRelease");

                    b.Navigation("SubApplication");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Pipeline", b =>
                {
                    b.HasOne("Domain.Entities.Pipelines.Templates.PipelineTemplate", "PipelineTemplate")
                        .WithMany()
                        .HasForeignKey("PipelineTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PipelineTemplate");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.PipelineJob", b =>
                {
                    b.HasOne("Domain.Entities.Pipelines.Pipeline", "Pipeline")
                        .WithMany("Jobs")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplate", b =>
                {
                    b.HasOne("Domain.Entities.Application", null)
                        .WithMany("PipelineTemplates")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("Domain.Entities.SubApplication", null)
                        .WithMany("PipelineTemplates")
                        .HasForeignKey("SubApplicationId");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplateJob", b =>
                {
                    b.HasOne("Domain.Entities.Pipelines.Templates.PipelineTemplateStage", "PipelineTemplateStage")
                        .WithMany("Jobs")
                        .HasForeignKey("PipelineTemplateStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineTemplateStage");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplateStage", b =>
                {
                    b.HasOne("Domain.Entities.Pipelines.Templates.PipelineTemplate", "PipelineTemplate")
                        .WithMany("Stages")
                        .HasForeignKey("PipelineTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineTemplate");
                });

            modelBuilder.Entity("Domain.Entities.SubApplication", b =>
                {
                    b.HasOne("Domain.Entities.Application", "ParentApplication")
                        .WithMany("SubApplications")
                        .HasForeignKey("ParentApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentApplication");
                });

            modelBuilder.Entity("iteration_requirements", b =>
                {
                    b.HasOne("Domain.Entities.Iteration", null)
                        .WithMany()
                        .HasForeignKey("iteration_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Requirement", null)
                        .WithMany()
                        .HasForeignKey("requirement_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("requirement_developers", b =>
                {
                    b.HasOne("Domain.Entities.Requirement", null)
                        .WithMany()
                        .HasForeignKey("requirement_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("requirement_followers", b =>
                {
                    b.HasOne("Domain.Entities.Requirement", null)
                        .WithMany()
                        .HasForeignKey("requirement_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.Navigation("PipelineTemplates");

                    b.Navigation("SubApplications");
                });

            modelBuilder.Entity("Domain.Entities.IntegrationRelease", b =>
                {
                    b.Navigation("ReleaseApps");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Pipeline", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplate", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Domain.Entities.Pipelines.Templates.PipelineTemplateStage", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Domain.Entities.SubApplication", b =>
                {
                    b.Navigation("PipelineTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
